<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_filtres_iad-list-item-title</name>
   <tag></tag>
   <elementGuidId>92c0a367-0d36-4378-980b-1932a2e7b25e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-agent-my-iad-contact/ui-view/iad-agent-my-iad-contact-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li/div/iad-list-item/iad-my-iad-contact-list-item/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/wis/agent/production/myiad/contact/1891679/edit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iad-list-item-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::{ 'is-disabled': $ctrl.contact.archived, 'is-readonly': $ctrl.isReadOnly }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>agent.production.myiad.contact.detail.edit.step({&quot;id&quot;:1891679,&quot;step&quot;:&quot;identity&quot;})</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>::$ctrl.srefOpts</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wis/agent/production/myiad/contact/1891679/edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iad-goto-top&quot;)/div[@class=&quot;container-fluid&quot;]/div[2]/iad-content-body[@class=&quot;ng-scope&quot;]/iad-agent-my-iad-contact[@class=&quot;ng-scope ng-isolate-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/iad-agent-my-iad-contact-list-page[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list myiad-contact-list&quot;]/iad-infinite-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-list&quot;]/iad-infinite-scroll[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-scroll ng-isolate-scope&quot;]/iad-list[@class=&quot;ng-scope ng-isolate-scope&quot;]/ul[@class=&quot;iad-list iad-list-grid&quot;]/li[@class=&quot;iad-list-item ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/iad-list-item[@class=&quot;ng-scope&quot;]/iad-my-iad-contact-list-item[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list-item myiad-contact-list-item&quot;]/div[@class=&quot;iad-list-item-title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-agent-my-iad-contact/ui-view/iad-agent-my-iad-contact-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li/div/iad-list-item/iad-my-iad-contact-list-item/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtres'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus récent au plus ancien'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquadd12929 Acquadd22929'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-my-iad-contact-list-item/div/div</value>
   </webElementXpaths>
</WebElementEntity>
