<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_dcisionnaire_if-mr</name>
   <tag></tag>
   <elementGuidId>233e781e-c639-482f-892b-4efacb50bcb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-agent-my-iad-contact/ui-view/iad-agent-my-iad-contact-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li[2]/div/iad-list-item/iad-my-iad-contact-list-item/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>if if-mr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iad-goto-top&quot;)/div[@class=&quot;container-fluid&quot;]/div[2]/iad-content-body[@class=&quot;ng-scope&quot;]/iad-agent-my-iad-contact[@class=&quot;ng-scope ng-isolate-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/iad-agent-my-iad-contact-list-page[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list myiad-contact-list&quot;]/iad-infinite-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-list&quot;]/iad-infinite-scroll[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-scroll ng-isolate-scope&quot;]/iad-list[@class=&quot;ng-scope ng-isolate-scope&quot;]/ul[@class=&quot;iad-list iad-list-grid&quot;]/li[@class=&quot;iad-list-item ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/iad-list-item[@class=&quot;ng-scope&quot;]/iad-my-iad-contact-list-item[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list-item myiad-contact-list-item&quot;]/div[@class=&quot;iad-list-item-title&quot;]/div[@class=&quot;iad-list-item-avatar&quot;]/i[@class=&quot;if if-mr&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-agent-my-iad-contact/ui-view/iad-agent-my-iad-contact-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li[2]/div/iad-list-item/iad-my-iad-contact-list-item/div/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/iad-list-item/iad-my-iad-contact-list-item/div/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
