<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_date-naissance_fa_fa-calendar</name>
   <tag></tag>
   <elementGuidId>8e3857c8-b6ec-429a-97a4-5bc8b0fed6c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-623-7158-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-identity-form/div/div/div[2]/div/iad-form-group/div/div/div/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'fa fa-calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-623-7158-panel&quot;)/div[@class=&quot;panel-body&quot;]/iad-my-iad-accordion-group-body[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-accordion-group-body&quot;]/ng-transclude[1]/div[@class=&quot;ng-scope&quot;]/iad-my-iad-contact-identity-form[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-pristine ng-valid myiad-form-node myiad-form-node-root physical_contact ng-valid-date&quot;]/div[@class=&quot;ng-scope myiad-form-node-row myiad-form-node-greetings&quot;]/div[@class=&quot;ng-scope myiad-form-node-col myiad-form-node-birth-date col-xs-12 col-sm-6&quot;]/div[@class=&quot;ng-scope myiad-form-node-group&quot;]/iad-form-group[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;iad-form-group form-group has-feedback&quot;]/div[@class=&quot;input-group ng-scope&quot;]/div[@class=&quot;input-group-addon&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-623-7158-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-identity-form/div/div/div[2]/div/iad-form-group/div/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-form-group/div/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-623-1642-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-identity-form/div/div/div[2]/div/iad-form-group/div/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
