<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_La date de facture est elle renseign _m_26bf6b</name>
   <tag></tag>
   <elementGuidId>94a3d9e6-13c6-49ab-bb00-6d83b95324f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-41 > label.mat-radio-label > div.mat-radio-container > div.mat-radio-outer-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-41']/label/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-outer-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-41&quot;)/label[@class=&quot;mat-radio-label&quot;]/div[@class=&quot;mat-radio-container&quot;]/div[@class=&quot;mat-radio-outer-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-41']/label/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-payment-interface-block-question[14]/form/div/mat-radio-group/mat-radio-button/label/div/div</value>
   </webElementXpaths>
</WebElementEntity>
