<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_filtres-house</name>
   <tag></tag>
   <elementGuidId>128f5e99-7304-417b-9da1-244d2cc7e455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.if.if-house</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-my-iad-project/ui-view/iad-agent-my-iad-project-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li/div/iad-list-item/iad-my-iad-project-list-item/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>if if-house</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iad-goto-top&quot;)/div[@class=&quot;container-fluid&quot;]/div[2]/iad-content-body[@class=&quot;ng-scope&quot;]/iad-my-iad-project[@class=&quot;ng-scope ng-isolate-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/iad-agent-my-iad-project-list-page[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list myiad-project-list ng-scope&quot;]/iad-infinite-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-list&quot;]/iad-infinite-scroll[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;iad-infinite-scroll ng-isolate-scope&quot;]/iad-list[@class=&quot;ng-scope ng-isolate-scope&quot;]/ul[@class=&quot;iad-list iad-list-line&quot;]/li[@class=&quot;iad-list-item ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/iad-list-item[@class=&quot;ng-scope&quot;]/iad-my-iad-project-list-item[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-list-item myiad-project-list-item&quot;]/div[@class=&quot;iad-list-item-title&quot;]/div[@class=&quot;iad-list-item-avatar&quot;]/i[@class=&quot;if if-house&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iad-goto-top']/div/div[2]/iad-content-body/iad-my-iad-project/ui-view/iad-agent-my-iad-project-list-page/div/iad-infinite-list/div/iad-infinite-scroll/div/iad-list/ul/li/div/iad-list-item/iad-my-iad-project-list-item/div/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-my-iad-project-list-item/div/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
